tasks:
    search_and_enter_contest:
        pause: 600
        immediate_start: true
        source:
            type: 'Tweet\Search'
            config: { q: 'RT follow', result_type: 'recent', count: 100, tweet_mode: 'extended', include_entities: true }
        steps:
            avoid_rt:
                type: 'Action\Tweet\RetrieveOriginalTweet'
            remove_duplicates:
                type: 'Condition\IsUnique'
            # Since the search API returns tweets with retweeted & favorited field always false
            # we need to reload each tweet to get the real values
            reload:
                type: 'Action\Tweet\Reload'
                config: { include_my_retweet: true, include_entities: true, tweet_mode: 'extended' }
            remove_already_rt:
                type: 'Condition\FieldComparison'
                config: { field: 'retweeted', operator: 'eq', value: false }
            remove_replies:
                type: 'Condition\FieldComparison'
                config: { field: 'in_reply_to_status_id', operator: 'eq', value: ~ }
            remove_too_old:
                type: 'Condition\FieldComparison'
                config: { field: 'created_at', operator: 'gte', value: '-10 DAYS' }
            remove_not_enough_retweeted:
                type: 'Condition\FieldComparison'
                config: { field: 'retweet_count', operator: 'gte', value: 50 }
            retweet:
                type: 'Action\Tweet\Retweet'
            favorite:
                type: 'Action\Tweet\Favorite'
                conditions:
                    -
                        type: 'Condition\FieldMatch'
                        config: { field: 'full_text', pattern: '/(fav|like)/i' }
            friendship_owner:
                type: 'Action\Tweet\FriendshipOwner'
                config: { follow: true }
            friendship_mentioned:
                type: 'Action\Tweet\FriendshipMentioned'
                config: { follow: true }
            display:
                type: 'Action\Tweet\Display'
