username: you@them.com
password: a_strong_password
tasks:
    demo_task:
        login_required: false
        start_delay: 0
        pause: 600
        source:
            type: 'Tweet\Search'
            config: { q: 'bot', result_type: 'recent', count: 5, tweet_mode: 'extended', include_entities: true }
        steps:
            display:
                type: 'Action\Tweet\Display'
