tasks:
    enter_contest:
        pause: 600
        start_immediatly: false
        steps:
            search:
                type: 'source'
                which: 'search'
                config: { q: 'RT follow gagner', lang: 'fr', result_type: 'recent', count: 100, tweet_mode: 'extended', include_entities: true }
            avoid_rt:
                type: 'action'
                which: 'retrieve_original_tweet'
            remove_duplicates:
                type: 'filter'
                which: 'is_unique'
            # Since the search API returns tweets with retweeted & favorited field always false
            # we need to reload each tweet to get the real values
            reload:
                type: 'action'
                which: 'reload'
                config: { include_my_retweet: true, include_entities: true, tweet_mode: 'extended' }
            remove_already_rt:
                type: 'filter'
                which: 'field_comparison'
                config: { field: 'retweeted', operator: 'eq', value: false }
            remove_replies:
                type: 'filter'
                which: 'field_comparison'
                config: { field: 'in_reply_to_status_id', operator: 'eq', value: ~ }
            remove_too_old:
                type: 'filter'
                which: 'field_comparison'
                config: { field: 'created_at', operator: 'gte', value: '-10 DAYS' }
            remove_not_enough_retweeted:
                type: 'filter'
                which: 'field_comparison'
                config: { field: 'retweet_count', operator: 'gte', value: 200 }
            retweet:
                type: 'action'
                which: 'retweet'
            favorite:
                type: 'action'
                which: 'favorite'
                conditions:
                    -
                        which: 'field_match'
                        config: { field: 'full_text', pattern: '/(fav|like)/' }
            friendship_owner:
                type: 'action'
                which: 'friendship_owner'
                config: { follow: true, ttl: '30 DAYS' }
            friendship_mentioned:
                type: 'action'
                which: 'friendship_mentioned'
                config: { follow: true, ttl: '30 DAYS' }
            reply:
                type: 'action'
                which: 'reply'
            display:
                type: 'action'
                which: 'display'

