tasks:
    contest:
        source:
            type: 'search'
            config:
                q: 'RT follow gagner'
                lang: 'fr'
                result_type: 'recent'
                count: 100

        filters:
            -
                type: 'field_comparator'
                config:
                    field: 'retweeted'
                    operator: 'eq'
                    value: true

        actions:
            - { type: 'retweet' }
            - { type: 'favorite' }
            - { type: 'friendship_owner', config: { follow: true, ttl: '30 DAYS' } }
            - { type: 'friendship_mentions', config: { follow: true, ttl: '30 DAYS' }  }
            -
                type: 'reply'
                config:
                    parts:
                        - Merci !
                    mentions:
                        conditions:
                            -
                                type: field_match
                                config:
                                    pattern: /(mention|ami|tag)/



        pause: 600

#    following_cleaning:
#        source:
#            type: following_expired
#        actions:
#            - { type: unfriendship }
#        pause: 3600
#        immediate_start: false # true by default
