tasks:
    contest:
        source:
            type: 'search'
            config:
                q: 'RT follow gagner'
                lang: 'fr'
                result_type: 'recent'
                include_entities: false
                count: 100

        filters:
            -
                type: 'field_comparator'
                config:
                    field: 'retweet'
                    operator: 'eq'
                    value: true

        actions:
            - { type: 'retweet' }
            - { type: 'favorite' }
            - { type: 'friendship_owner', config: { follow: true, ttl: '30 DAYS' } }
            - { type: 'friendship_mentions', config: { follow: true, ttl: '30 DAYS' }  }
            - { type: 'reply' }

        pause: 600

    followers_cleaning:
        source:
            type: clear_followers
        pause: 3600
        immediate_start: false # true by default
