parameters:
    configuration.file: ~
    browser.headless: true

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Twist\:
        resource: '../src/*'
        exclude:  '../src/Twitter/Task/*'

    Psr\Container\ContainerInterface:
        synthetic: true
        public: true

    # TWITTER
    HeadlessChromium\BrowserFactory:
        arguments: ['chromium-browser']

    Twist\Twitter\Browser\Client:
        arguments:
            $headersInterceptorScript: '%root_dir%/src/Twitter/Browser/Resource/headers-interceptor.js'
            $requestProxyScript: '%root_dir%/src/Twitter/Browser/Resource/request-proxy.js'
            $browserOptions: { headless: '%browser.headless%' }

    Twist\Twitter\Task\:
        resource: '../src/Twitter/Task/*'
        exclude:  '../src/Twitter/Task/{TaskFactory.php,Task.php,Step/Action/ConditionalAction.php}'
        shared: false
        public: true

    Twist\Twitter\Task\TaskFactory: ~

    Twist\Twitter\Repository\FriendshipRepository:
        factory: ['@Doctrine\ORM\EntityManager', 'getRepository']
        arguments: ['Twist\Twitter\Entity\Friendship']

    # CONFIGURATION
    Symfony\Component\Yaml\Parser: ~

    Symfony\Component\Serializer\Encoder\YamlEncoder:
        arguments:
            $defaultContext: { yaml_inline: 10 }

    Symfony\Component\Serializer\SerializerInterface: '@Symfony\Component\Serializer\Serializer'

    Symfony\Component\Serializer\Serializer:
        arguments:
            $encoders: ['@Symfony\Component\Serializer\Encoder\YamlEncoder']

    Twist\Configuration\Configuration:
        arguments:
            $defaultConfigFile: '%root_dir%/config/default.yaml'
            $parser: '@Symfony\Component\Yaml\Parser'
            $storagePath: '%configuration.file%'

    # CONSOLE
    Twist\Console\Command\:
        resource: '../src/Console/Command/*'
        public: true
        tags: [{ name: 'twist.command' }]

    Psr\Log\LoggerInterface: '@Twist\Console\Logger\ConsoleLogger'
    Twist\Scheduler\TaskFollowerInterface: '@Twist\Console\Task\TaskFollower'

    Symfony\Component\Console\Input\InputInterface:
        synthetic: true
        public: true

    Symfony\Component\Console\Output\OutputInterface:
        synthetic: true
        public: true

    Symfony\Component\Console\Style\SymfonyStyle: ~

    # DOCTRINE
    Doctrine\ORM\EntityManager:
        factory: ['@Twist\Doctrine\EntityManagerFactory', 'create']
        arguments:
            $paths: ['%root_dir%/src/Twitter/Entity']
