parameters:
    kernel.secret: ~

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude:  '../src/Twitter/Task/*'

    Psr\Container\ContainerInterface:
        synthetic: true
        public: true

    # TWITTER
    HeadlessChromium\BrowserFactory:
        arguments: ['chromium-browser']

    HeadlessChromium\Browser:
        factory: ['@HeadlessChromium\BrowserFactory', 'createBrowser']
#        arguments: [headless: false]

    App\Twitter\Browser\Client:
        arguments:
            $headersInterceptorScript: '%root_dir%/src/Twitter/Browser/Resource/headers-interceptor.js'
            $requestProxyScript: '%root_dir%/src/Twitter/Browser/Resource/request-proxy.js'

    App\Twitter\Task\:
        resource: '../src/Twitter/Task/*'
        exclude:  '../src/Twitter/Task/{TaskFactory.php,Task.php,Step/Action/ConditionalAction.php}'
        shared: false
        public: true

    App\Twitter\Task\TaskFactory: ~

    # CONFIGURATION
    Symfony\Component\Yaml\Parser: ~

    Symfony\Component\Serializer\Encoder\YamlEncoder:
        arguments:
            $defaultContext: { yaml_inline: 10 }

    Symfony\Component\Serializer\SerializerInterface: '@Symfony\Component\Serializer\Serializer'

    Symfony\Component\Serializer\Serializer:
        arguments:
            $encoders: ['@Symfony\Component\Serializer\Encoder\YamlEncoder']

    App\Configuration\Configuration:
        arguments:
            $defaultConfigFile: '%root_dir%/config/default.yaml'
            $parser: '@Symfony\Component\Yaml\Parser'
        calls:
            - ['load']

    # CONSOLE
    Psr\Log\LoggerInterface: '@App\Console\Logger\ConsoleLogger'
    App\Scheduler\TaskFollowerInterface: '@App\Console\Task\TaskFollower'

    Symfony\Component\Console\Input\ArgvInput: ~
    Symfony\Component\Console\Input\InputInterface:
        alias: 'Symfony\Component\Console\Input\ArgvInput'
        public: true

    Symfony\Component\Console\Output\ConsoleOutput:
        arguments:
            $verbosity: !php/const Symfony\Component\Console\Output\OutputInterface::VERBOSITY_VERY_VERBOSE
    Symfony\Component\Console\Output\OutputInterface:
        alias: 'Symfony\Component\Console\Output\ConsoleOutput'
        public: true

    Symfony\Component\Console\Style\SymfonyStyle: ~

    Symfony\Component\Console\Application:
        calls:
            - ['add', ['@App\Console\Command\TwitterCommand']]
            - ['add', ['@App\Console\Command\GenerateReplyCommand']]
            - ['setDefaultCommand', [!php/const App\Console\Command\TwitterCommand::COMMAND_NAME, false]]
        public: true
